name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install beautifulsoup4
      - name: Lint
        run: |
          flake8 --exit-zero
      - name: Test
        run: |
          pytest -q
      - name: Validate commit
        run: |
          python scripts/validate_commit.py
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
